config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :twiits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'twiits#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twiit.rb
class Twiit < ApplicationRecord
  validates :twiit, length: { minimum: 1 }
  belongs_to :user, foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :twiits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password, :password_confirmation])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/twiits_controller.rb
class TwiitsController < ApplicationController
  before_action :set_twiit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /twiits
  # GET /twiits.json
  def index
    @twiits = Twiit.all.order("created_at DESC")
    @twiit = Twiit.new
  end

  # GET /twiits/1
  # GET /twiits/1.json  

  def show
    @twiit = Twiit.find(params[:id])
  end

  # GET /twiits/new
  def new
    @twiit = current_user.twiits.build
  end

  # GET /twiits/1/edit
  def edit
    @twiit = Twiit.find(params[:id])
  end

  # POST /twiits
  # POST /twiits.json
  def create
    @twiit = current_user.twiits.build(twiit_params)

    respond_to do |format|
      if @twiit.save
        format.html { redirect_to root_path, notice: 'Twiit was successfully created.' }
        format.json { render :show, status: :created, location: @twiit }
      else
        format.html { redirect_to root_path, notice: "Twiit not posted :(" }
        format.json { render json: @twiit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twiits/1
  # PATCH/PUT /twiits/1.json
  def update
    respond_to do |format|
      if @twiit.update(twiit_params)
        format.html { redirect_to @twiit, notice: 'Twiit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twiit }
      else
        format.html { render :edit }
        format.json { render json: @twiit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twiits/1
  # DELETE /twiits/1.json
  def destroy
    @twiit.destroy
    respond_to do |format|
      format.html { redirect_to twiits_url, notice: 'Twiit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twiit
      @twiit = Twiit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twiit_params
      params.require(:twiit).permit(:twiit, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twiits_helper.rb
module TwiitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/774f0ae2db.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="notification"> <%= alert %> </p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twiitter</h1>
        <% end %>      
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>        
        </div>
      </div>
      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end mr-4">
          <div class="field is-grouped custom-centered">
            <p class="control">
              <%= link_to  "New Twiit", root_path, class: "button is-info is-inverted has-text-centered" %>
            </p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to  current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to  "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
              </p>
            <% else %>
              <p class="control">
                <%= link_to  "Log In", new_user_session_path, class:"button is-info" %>
                </p>
              <p class="control">
                <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/twiits/_feed.html.erb
<div class="column is-half">
  <%= render 'form' %>
  <% @twiits.each do | twiit | %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(twiit.user.email, size: 64, alt: twiit.user.name) if twiit.user %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= twiit.user ? twiit.user.name : "Someone twiited:" %></strong><br>
            <small><%=  twiit.user ? "@#{twiit.user.username}" : "user no longer here" %></small><br><br>
            <p><%= twiit.twiit %></p><br>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to twiit, class: "level-item" do %>
                <span class="icon"><i class="fas fa-link" aria-hidden="true"></i></span>
              <% end %>
              <% if twiit.user && twiit.user == current_user %>
                <%= link_to edit_twiit_path(twiit[:id]), class: "level-item" do %>
                  <span class="icon"><i class="fas fa-pencil-alt" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to  twiit, method: :delete, data: {  confirm: "Are you sure you want to delete this twiit?" } do %>
                <span class="icon"><i class="fas fa-trash-alt" aria-hidden="true"></i></span>
                <% end %>
              <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/twiits/_form.html.erb
<article class="media box">
  <% if user_signed_in? %>
    <figure class="media-left">
      <p class="image is-64x64">
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
      </p>
      <p> <%= current_user.username if user_signed_in? %> </p>
    </figure>
  <% end %>
  <div class="media-content">       
    <%= simple_form_for @twiit do |f| %>
      <%= f.error_notification %>
      <div class="field">
        <div class="control">
          <%= f.input :twiit,
                      label: 'Twiit about something',
                      input_html: {class: "textarea"},
                      wrapper: false, label_html: { class: "label" },
                      placeholder: "Compose a new twiit",
                      autofocus: true
          %>
        </div>
      </div>
      <%= f.button :submit, class: "button is-info"%>
    <% end %>
  <div>
</article>

app/views/twiits/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>

          </figure>
        </div>
        <div class="media-content">
          <p>
            <strong> <%= current_user.name %> </strong><br>
            <small> <%= "@#{current_user.username}" %></small>
          </p>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6">
              <%= current_user.twiits.count %>
            </p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6">500K</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">43</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/twiits/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a href="" class="panel-block">Trend 1</a>
    <a href="" class="panel-block">Trend 2</a>
    <a href="" class="panel-block">Trend 3</a>
    <a href="" class="panel-block">Trend 4</a>
    <a href="" class="panel-block">Trend 5</a>
    <a href="" class="panel-block">Trend 6</a>
    <a href="" class="panel-block">Trend 7</a>
    <a href="" class="panel-block">Trend 8</a>
  </nav>
</div>

app/views/twiits/_who_to_follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
          <p>
            <strong>Abdullah Numan</strong>
            <small>@aanuman15</small>
          </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
          <p>
            <strong>Abdullah Numan</strong>
            <small>@aanuman15</small>
          </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
          <p>
            <strong>Abdullah Numan</strong>
            <small>@aanuman15</small>
          </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
          <p>
            <strong>Abdullah Numan</strong>
            <small>@aanuman15</small>
          </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
          <p>
            <strong>Abdullah Numan</strong>
            <small>@aanuman15</small>
          </p>
          </div>
        </div>
      </article>
    </div>
  </nav>
</div>

app/views/twiits/edit.html.erb
<%= render 'form', twiit: @twiit %>

app/views/twiits/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if current_user %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who_to_follow'%>
    </div>
  </div>
</section>

app/views/twiits/new.html.erb
<div class="section">
  <div class="container">
    <div class="column is-half is-centered">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/twiits/show.html.erb
<p id="notice"><%= notice %></p>
<div class="section">
  <div class="container">
    <div class="column is-centered">
      <article class="media">
        <div class="media-left">
          <figure class="image is64x64">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= @twiit.user ? "#{@twiit.user.name} twiitted:" : "Someone twiitted:" %></strong><br>
            <small><%=  @twiit.user ? "@#{@twiit.user.username}" : "user no longer here" %></small><br><br>
            <p><%= @twiit.twiit %></p><br>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <% if @twiit.user && @twiit.user == current_user %>
                <%= link_to edit_twiit_path(@twiit), class: "level-item" do %>
                  <span class="icon"><i class="fas fa-pencil-alt" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to  @twiit, method: :delete, data: {  confirm: "Are you sure you want to delete this twiit?" } do %>
                <span class="icon"><i class="fas fa-trash-alt" aria-hidden="true"></i></span>
                <% end %>
              <% end %>
            </div>
          </nav>
        </div>
      </article>
      <br>
      <%= link_to 'Back to Feed', twiits_path %>
    </div>
  </div>
</div>